import type { BlogPost } from "@/lib/blog-helpers";
import { p, h2, img, tweet } from "@/lib/blog-helpers";
// Source: https://x.com/zKorp_/status/2020887605378789676

const post: BlogPost = {
  slug: "qsdqsdqsdqsdsd",
  date: "Feb 8, 2026",
  dateISO: "2026-02-08",
  category: "Event Coverage",
  title: "qsdqsdqsdqsdsd",
  excerpt: "testqskdfljqsdlkjqsd",
  accent: "#8B5CF6",
  tags: ["zkorp"],
  readTime: "5 min",
  author: "Steven Klinger",
  authorHandle: "@scabanel_",
  coverImage: "/blog/qsdqsdqsdqsdsd/qsdqsdqsdqsdsd-1.jpg",
  content: [
    p("It’s 2026. The click-to-earn era is behind us. We are now truly entering the age of the autonomous world and one ecosystem is defining the new standard."),
    p("Here is the full zKorp thesis on Realms, Eternum, and Blitz."),
    tweet("2019068428066189410"),
    h2("ACT I: Onchain games with true mechanics"),
    p("If you were around at the beginning, you remember the promise of Web3 gaming."),
    p("It was loud, chaotic, and frankly, disappointing. We were sold \"financial freedom\" disguised as video games: basic click-loops masked by flashy tokens. It was…messy."),
    p("Sometimes, creative projects emerged, like"),
    img("/blog/qsdqsdqsdqsdsd/qsdqsdqsdqsdsd-1.jpg", "image"),
    p("Fast forward to 2026. The dust has settled, and the industry has matured."),
    p("As we speak, we are working at"),
    p("with major onchain games of the ecosystem to help them build strong technical features."),
    p("Our job is to understand the cutting edge of Web3 technology. We don't just audit smart contracts, we stress-test entire ecosystems. And right now, there is one project that stands above the rest in terms of technical ambition and execution: Realms ("),
    h2("ACT II: Why put gaming onchain?"),
    p("Before we dive into Realms, we need to answer the skeptic’s question (legitimate one btw): Why bother putting complex game logic on a blockchain? Is it even possible?"),
    p("You must know that since the 1970s, the gaming industry has undergone massive shifts: from arcades to consoles, to mobile, and finally to the massive $200B+ market we see today."),
    p("It’s the good timing to tell again that Clair Obscur is from our home : vive la France! 🇫🇷 🥐"),
    img("/blog/qsdqsdqsdqsdsd/qsdqsdqsdqsdsd-2.jpg", "image"),
    p("By putting the entire game state and logic on, games unlock three strong features:"),
    p("True Permanence: As long as Ethereum exists, the game exists. No server shutdowns."),
    p("Free contributions: This is the killer feature. Because the game logic is public code, any developer can build his own client, without asking for permission. They can build better UIs, automated trading bots, or even entirely new games that use the same assets. One of our tech, <a href=\"https://x.com/Djizus\" target=\"_blank\" rel=\"noopener noreferrer\">@Djizus</a>, heavily contributed to several games that way, like Realms btw."),
    p("Total transparency: Do we really have to explain that to you?"),
    p("Starknet allows complex games like"),
    p("to run entirely on-chain without bankrupting players on gas fees."),
    p("Who loves fees here?….Well? That’s what we thought."),
    h2("ACT III: The Realms ecosystem. Two games, two strong experiences."),
    p("Realms ecosystem is governed by their DAO and powered by a single economic engine: the"),
    tweet("1877626914569072843"),
    p("Realms has two babies: Eternum and Realms Blitz: two different games for two different kind of players."),
    p("Eternum: The long-term strategy game"),
    p("Eternum cames first (we saw you). It’s a slow-burn, high-stakes strategy game that plays out over weeks."),
    p("The Loop: You govern a Realm, manage resources, and build armies."),
    p("The Depth: It’s not just about building; it’s about politics. To win, you must form alliances, trade resources on an open market (AMMs), and—inevitably—betray your neighbors."),
    p("This attracts not just gamers, but syndicates and DAOs who play to win."),
    p("Realms Blitz: two hours, battle centric game"),
    p("If Eternum is a marathon, Blitz is a sprint for you, less-patient ones!"),
    p("The Loop**:** Fast-paced, 2-hour games. It’s a pure RTS experience akin to Age of Empires or Starcraft."),
    p("The Tech**:** Blitz proves that high-speed gaming is possible onchain. It condenses the complex economy of Eternum into a session-based format where raw skill determines the winner."),
    img("/blog/qsdqsdqsdqsdsd/qsdqsdqsdqsdsd-3.jpg", "image"),
    p("Realms Blitz: gathering ressources but mostly bring pain to your opponents!"),
    p("And at this game, not only"),
    p("is a skill tech specialist in our company, he is also the 1st world player on Blitz!"),
    img("/blog/qsdqsdqsdqsdsd/qsdqsdqsdqsdsd-4.jpg", "image"),
    p("He likes to flex so he kinda forced us to show you this."),
    h2("ACT IV:  Real tech, real gameplay"),
    p("Being able to both understand the tech, helping building and contributes to this ecosystem makes us better players."),
    p("Like Djizus said (what a thing to write!) : “When you understand the smart contracts behind the game, you see the Matrix. You understand exactly how the economy flows, where the inefficiencies are, and how to exploit them. It’s just a good game that pays you for being smart.\""),
    p("At zKorp, we are only working on projects we truly like and where our tech expertise is needed, obviously."),
    p("That’s why we can’t tell you without fear that Realms is one of the most technically ambitious onchain game of all time for now."),
    p("A true proof of onchain gaming can be true games now."),
    p("Final ACT: Community is everything, as always"),
    p("Is this still niche? Maybe. But the signs of mass adoption are there."),
    p("At DevConnect Argentina 2025, Thomas saw Blitz being played on a main stage with a full esports setup, displaying real-time gameplay just like any major Web2 title!"),
    p("Cumberlord hosted this livestreamed game wearing a full knight cosume: peak content I have to tell !"),
    img("/blog/qsdqsdqsdqsdsd/qsdqsdqsdqsdsd-5.jpg", "image"),
    p("Whether you are a developer looking to contribute to an open-source world or a strategist ready to conquer the map, the Realms universe is open."),
    p("Don’t forget to watch our full video breakdown"),
    p("to see the gameplay in action. Also…Djizus intervenes to give you few tips and to challenge you! (He has a huge ego excuse him)")
  ],
};

export default post;
