import type { BlogPost } from "@/lib/blog-helpers";
import { p, h2, cta } from "@/lib/blog-helpers";
// Source: https://x.com/Scabanel_/status/2039269652354801678

const post: BlogPost = {
  slug: "web3-test",
  date: "Mar 31, 2026",
  dateISO: "2026-03-31",
  category: "Event Coverage",
  title: "Web3 Test",
  excerpt: "",
  accent: "#8B5CF6",
  tags: ["zkorp"],
  readTime: "7 min",
  author: "Steven Klinger",
  authorHandle: "@scabanel_",
  content: [
    p("ScabanelETHCC CANNES"),
    p("![image](https://pbs.twimg.com/media/HERmPQAbYAMeIX5?format=jpg&name=large)"),
    p("How I speedran NFTs in 30 days (and got scammed along the way)"),
    p("Few weeks ago, I didn’t even own a crypto wallet and I genuinely thought the NFT space was strictly about trading monkey pictures at ridiculous prices (I was not THAT far from the truth but nvm)."),
    p("But you know what? I had to learn."),
    p("Onboarding on Web3 is truly a b**ch"),
    p("When I had to create a wallet, I first had to figure out how to put money in it without getting drained by crazy intermediary fees and gas (who loves it?….Exactly)"),
    p("I understand the need, but it is annoying to pay more just because you do not know enough yet. I will skip the details of my struggles, but between hot wallets and cold wallets, it took me a good amount of time to understand how all of this worked."),
    p("It ended up with multiple wallets (took me a while to get that this was pretty common), and a"),
    p("That was my first entry into onchain gaming by the way, I might talk about it later, here or via"),
    p("Cartridge Controller"),
    p("![image](https://pbs.twimg.com/media/HERhER0WkAAHZnw?format=jpg&name=large)"),
    p("My beloved beasts! It’s nothing, but it’s honest work!"),
    p("Once swaps, bridges, reading the chain, wallets, and the different assets finally clicked, I could focus on digging into other subjects."),
    p("I’m an obsessive learner"),
    p("When I’m interessed in something, I get… kind of obsessed. I can spend a massive amount of time on it over a short period. That is partly what makes me a good professional. I can ingest a crazy amount of information on domains I know nothing about and very quickly build bridges toward commercial or marketing interests."),
    p("So, I wanted to better understand the NFT universe. The Normies project was a huge gateway for that. My team at zKorp told me I was going to fall into a rabbit hole where all I would do is get scammed and lose money (which happened, obviously), but the first project that caught my eye was Normies, created by"),
    cta("tweet", "https://x.com/serc1n/status/2023910207407968370"),
    p("Lucky me, I got a few very early. Including one on secondary before the reveal thanks to"),
    p(", thanks man, you are a brother (and a super pleasant client to work with, btw)."),
    p("One of them was a rare one (Alien type). That is where I saw the obvious parallel and the absolute gambling danger you can find with Pokémon cards (a rabbit hole I escaped, thank God)."),
    h2("My $60 scam lesson"),
    p("You simply cannot avoid being scammed in this ecosystem. I was cocky enough to think it would never happen to me. You know what happened? I got scammed, big surprise!"),
    p("It was while wandering through the NFT ecosystem that I got scammed buying a fake, unrevealed limited edition Normie... simply because it was sitting in Serc's portfolio!"),
    p("I learned later that since you can airdrop anything to anyone without their approval, these things happen every tiiiiiiime."),
    p("![image](https://pbs.twimg.com/tweet_video_thumb/HERhztfX0AApVxm.jpg?format=jpg&name=large)"),
    p("Goodbye my $60, I learned the hard way!"),
    p(", you have some very embarrassing DMs from me, a beginner in the ecosystem thinking I dismantled a massive scam ring when I was just a naive pigeon."),
    p("Deep into NFT roots and vision"),
    p("Chatting with several people gave me a lot of information. But I needed more…as concrete knowledge so I wanted books because…books are great that’s it!"),
    p("Serc advised me three books to learn more about NFT art and history."),
    p("Free to Claim about Cryptopunks history."),
    p("On NFTs about the global history of art in NFTs."),
    p("And Not DED, which I could not find a good copy of so I quickly moved on."),
    p("![image](https://pbs.twimg.com/media/HERj4HuWMAAFWBM?format=jpg&name=large)"),
    p("That's good, I don't know what can I tell you more about it honestly!"),
    p("And it is true that there are so many interesting things to take away from this."),
    p("On the narrative, on the artists' vision, but mostly on something I really did not expect and that I think I like the most. The tech behind some collections."),
    p("The ability to build on an open-source collection and make its API public. That was part of the Normies value proposition on day one, and other projects are increasingly taking that path. Funny enough, Cryptopunks only started doing this very recently!"),
    p("To call it an inspiration... might be a stretch."),
    cta("tweet", "https://x.com/nodefnd/status/2032510432712499629"),
    p("The Verse universe and Human Resources"),
    p("Speaking of tech. This is also the moment to talk about my encounter with the Human Resources ecosystem by Tabor Robak and the Verse marketplace."),
    cta("tweet", "https://x.com/Tabcorp_HR/status/2033302195181863332"),
    p("First, let’s talk about"),
    p(", totally different approach and projects in comparison to Opensea. Fewer scams, much bigger deals (totally out of my range) and a great artists community."),
    p("And I’m not gonna lie, I know nothing about art itself so I’m trying to learn that too you know."),
    p("![image](https://pbs.twimg.com/media/HERkYvdWkAEuyT7?format=jpg&name=large)"),
    p("Verse's website is cleaaaaaan!"),
    p("Human Resources is a project that started on Verse, mint was there and it’s really tied to it."),
    p("Actually, the marketplace is very invested in this project and it surprised me at first! Also, people are very opened to talk (mostly) and to give art inspirations so I learned a not with them, thanks🫡"),
    p("So…what’s Human Resources? Profiles generated by multiple algorithms imagined by the artist, with an NFT design acting like dolls. A base pattern where you can put basically whatever you want, a totally quirky narrative, and completely undesired rendering glitches that result in a really cool collection!"),
    cta("tweet", "https://x.com/TaborRobak/status/2010038615443697668"),
    p("This is where I hit my reflection on the boundary between investment, profitability, art, and respecting the art."),
    p("Like many on X before me (and after me), I started over-selling the project, and one of my NFTs in particular that was rare because it was \"bugged.\" I will keep it short."),
    p("Looking back, I probably did too much promoting it. When I sold it, people definitely called me out on it. It triggered a reflection on my end and a short conversation with the artist to understand where I was \"wrong.\""),
    p("Well, it turns out there is the team of convinced artists who collect for the love of art, the opportunists who come to make a quick buck, and a blurry line defined by no one on \"when it is acceptable to sell.\" Someone also dropped the term \"sell shaming\" on me, and I was mostly just getting trolled."),
    p("I come from gaming, I am a former tech guy, I am over 30, and I still take massive baits."),
    p("Fair enough. I am learning too. I will definitely not do that again in the future,"),
    p("I was cringe, and it is not the approach I want to have: see for yourself."),
    cta("tweet", "https://x.com/Scabanel_/status/2033677440489345441"),
    p("Art meets business meets speculation meets tech meets…people."),
    p("Even though I will never say I do not have an investment and profitability mindset in this. Let us not lie to ourselves, the overwhelming majority of people are here for that. I also have that interest in mind, even if it is not the only one. Profitability takes other forms than just a \"positive\" sale anyway but still, can we really not talk about money when we are into the crypto universe?"),
    p("Regardless, all these encounters. The scammy AI projects, the copycats, the ambitious technical projcts with interesting narratives like Normies and Human Resources."),
    p("But also others I find really great like Good Vibes Club, Chimpers, and the recent Del Mundos. And the very niche artistic projects on exclusive platforms like Verse, or directly minting on an independent artist's site. All of this inspires me a lot, both professionally and in terms of pure creation!"),
    p("I actually created a big webApp project. A real-time 3D \"life\" simulation on our planet of all the unburned Normies, with different behaviors based on their traits and different dialogues depending on their situations and movements...stay tuned for that!"),
    p("![image](https://pbs.twimg.com/media/HERlQu0aMAA4MPV?format=jpg&name=large)"),
    p("First glance at it! “Pas mal non? C'est français.”"),
    p("You can see the world on action here:"),
    p("https://just-a-normie-world.vercel.app/"),
    p("What next? It’s IRL time ofc."),
    p("Next step in the Web3 ecosystem. My trip to"),
    p("with zKorp's team to build, represent the company and what we do there, work with one of our clients on site, meet great people, and gather even more knowledge!"),
    p("But also, I will continue to deep dive into several projects, talking with people and sharing my journey here and there."),
    p("Building takes several forms anyway 🫡")
  ],
};

export default post;
